dist: trusty
sudo: required

services:
  - docker

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - sudo pip install ansible
  # Install sshpass
  - sudo apt-get install -y sshpass

deploy:
  - provider: script
    script: bash deploy.sh blue
    on:
      branch: master
  - provider: script
    script: bash deploy.sh green
    on:
      branch: beta